### ISSUE TITLE
plotly_event conflict with st.plotly_chart(fig, use_container_width=True)

### ISSUE THREAD

**Issue by b-y-f** [streamlit/component-template#26]
when use both together one more plot with be shown

Like this one two plot appears
```python
fig = px.scatter_mapbox(df, lat="lat", lon="lon", zoom=4, height=800)
fig.update_layout(mapbox_style="open-street-map")


selected_points = plotly_events(fig)

if selected_points:
    st.write(df.iloc[selected_points[0]['pointIndex']].astype(str))

st.write("Total points:", df.shape[0])
st.plotly_chart(fig, use_container_width=True)
```

**Comment by sfc-gh-kbregula** [comment]
Hi @b-y-f 👋

Thanks for sharing this question! We use GitHub Issues for bugs that impact the templates as a whole; since this error is specific to your app and your use of [Streamlit Plotly Events](https://github.com/yihui-he/streamlit-plotly-events), do you mind sharing it in [our forum](https://discuss.streamlit.io/) instead?
