### ISSUE TITLE
Optional tooltip

### ISSUE THREAD

**Issue by sogoogos** [streamlit/component-template#50]
Regarding [this issue](https://github.com/streamlit/streamlit/issues/6642), it would be great if this template has the functionality to give a component an optional tooltip just like other Streamlit components with `help=`.

**Comment by sfc-gh-kbregula** [comment]
The template is just a base for other components. You can copy it and adapt it to your needs. If you need to, you can even use external libraries like [react-tooltip](https://www.npmjs.com/package/react-tooltip) to address our user case.

We use GitHub Issues for bugs that impact the open-source library as a whole; since this issue is specific to your component, do you mind sharing it in [our forum](https://discuss.streamlit.io/) instead?
