### ISSUE TITLE
Remove bootstrap from template

### ISSUE THREAD

**Issue by domoritz** [streamlit/component-template#6]
It doesn't seem to be required in all cases so it would be good to remove it.

**Comment by tconkling** [comment]
Currently, auto-sizing of component iframes in both templates relies on bootstrap's presence (because bootstrap sets up some sane defaults for margins and paddings and whatnot that make `document.body.scrollHeight` report the actual visible size of the iframe - getting metrics for the bounds of the DOM is stupidly non-trivial and inefficient otherwise).

However! We are planning to pull out of the subset of bootstrap that we actually rely on into a smaller CSS (that also includes some Streamlit theming). It's on the roadmap but not yet scheduled.

**Comment by domoritz** [comment]
Ahh, I see. Does it make sense to add `import 'bootstrap/dist/css/bootstrap.min.css';` to `index.ts` instead of importing in the `index.html` page?

**Comment by tconkling** [comment]
Could do - actually, that's how we wrote things originally. But there are a couple nice things about including it in the HTML - the biggie is that we take advantage of the browser's cache. (Arguably, we should use a CDN for this...)

The other minor advantage is that the CSS loads before the DOM is built. (In practice, I don't think makes a difference for these components.)

Are you asking because it would make it clearer to have it in the code?

**Comment by domoritz** [comment]
> Are you asking because it would make it clearer to have it in the code?

It's weird to depend on bootstrap but then have the css file copied in the component rather than just loading it from node_modules.

**Comment by tconkling** [comment]
Oh! I didn't realize we were still doing that. I agree - I'll remove it from package.json.
